from __future__ import annotations

import csv
import io
import json
from pathlib import Path
import sys
import zipfile

import pytest

ROOT = Path(__file__).parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from usb_logic_trace_correlator.saleae_sal import (
    extract_digital_channels_from_sal_bytes,
    extract_i2c_csv_from_sal_bytes,
    inspect_sal_bytes,
)
from usb_logic_trace_correlator.saleae_sal_native import (
    SaleaeSalDecodeError,
    decode_digital_channels_from_sal_bytes,
    decode_i2c_csv_from_sal_bytes,
)

# Fixed, precomputed Saleae digital-v2 fixtures for one transaction:
# START, write address 0x67, data 0x3A, address/data ACK, STOP at 1 MHz.
# These bytes are intentionally frozen rather than generated by a test-side
# copy of the production decoder/encoder logic.
_SDA_BIN = bytes.fromhex(
    "3c53414c4541453e020000006400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dc0000000000000001000b00000000000000090413131d271d09091d0e"
)
_SCL_BIN = bytes.fromhex(
    "3c53414c4541453e020000006400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dc00000000000000010027000000000000000e0404040404040404040404040404040404040404040404040404040404040404040404040413"
)


def _make_sal(*, version_override: int | None = None, include_i2c: bool = True) -> bytes:
    sda = bytearray(_SDA_BIN)
    scl = bytearray(_SCL_BIN)
    if version_override is not None:
        sda[8:12] = int(version_override).to_bytes(4, "little")
        scl[8:12] = int(version_override).to_bytes(4, "little")

    analyzers = []
    if include_i2c:
        analyzers.append(
            {
                "type": "I2C",
                "name": "I2C",
                "settings": [
                    {"title": "SDA", "setting": {"value": 0}},
                    {"title": "SCL", "setting": {"value": 1}},
                ],
            }
        )

    meta = {
        "version": 20,
        "data": {
            "captureStartTime": "2026-09-07T10:00:00+08:00",
            "legacySettings": {"sampleRate": {"digital": 1_000_000}},
            "analyzers": analyzers,
            "rowsSettings": [
                {
                    "type": "channel",
                    "name": "DATA",
                    "channel": {"type": "Digital", "deviceChannel": 0},
                },
                {
                    "type": "channel",
                    "name": "CLK",
                    "channel": {"type": "Digital", "deviceChannel": 1},
                },
            ],
        },
        "binData": [
            {"type": "Digital", "deviceChannel": 0, "file": "./digital-0.bin"},
            {"type": "Digital", "deviceChannel": 1, "file": "./digital-1.bin"},
        ],
    }

    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("meta.json", json.dumps(meta))
        zf.writestr("digital-0.bin", bytes(sda))
        zf.writestr("digital-1.bin", bytes(scl))
    return output.getvalue()


def test_inspect_sal_reports_native_i2c_support_and_digital_rate() -> None:
    info = inspect_sal_bytes(_make_sal())

    assert info.ok is True
    assert info.sample_rate_hz == 1_000_000
    assert info.native_i2c_decodable is True
    assert info.digital_channel_names == {0: "DATA", 1: "CLK"}
    assert "I2C" in info.analyzers


def test_decode_i2c_csv_from_fixed_digital_v2_fixture() -> None:
    csv_text = decode_i2c_csv_from_sal_bytes(_make_sal())
    rows = list(csv.DictReader(io.StringIO(csv_text)))

    assert rows == [
        {
            "Time [s]": "0.000010000",
            "Address": "0x67",
            "Read/Write": "write",
            "Data": "3A",
            "ACK": "ACK",
            "Summary": "native_sal; termination=stop; trailing_bits=1",
        }
    ]


def test_extract_i2c_csv_fails_closed_for_unvalidated_binary_version() -> None:
    sal = _make_sal(version_override=3)
    info = inspect_sal_bytes(sal)

    assert info.ok is True
    assert info.native_i2c_decodable is False
    assert "version 3" in (info.native_i2c_reason or "")
    assert extract_i2c_csv_from_sal_bytes(sal) is None
    assert extract_digital_channels_from_sal_bytes(sal) is None
    with pytest.raises(SaleaeSalDecodeError, match="version 3"):
        decode_i2c_csv_from_sal_bytes(sal)


def test_extract_i2c_csv_requires_unambiguous_i2c_analyzer() -> None:
    sal = _make_sal(include_i2c=False)

    assert extract_i2c_csv_from_sal_bytes(sal) is None


def test_decode_digital_channels_preserves_names_and_transition_samples() -> None:
    channels = decode_digital_channels_from_sal_bytes(_make_sal())

    assert [(channel.channel, channel.name, channel.initial_state, channel.end_sample) for channel in channels] == [
        (0, "DATA", 1, 220),
        (1, "CLK", 1, 220),
    ]
    assert [transition.sample for transition in channels[0].transitions] == [
        10, 15, 35, 55, 85, 125, 155, 165, 175, 205
    ]
    assert [(transition.state, transition.edge) for transition in channels[0].transitions[:2]] == [
        (0, "falling"),
        (1, "rising"),
    ]


def test_extract_digital_channels_fails_closed_for_invalid_archive() -> None:
    assert extract_digital_channels_from_sal_bytes(b"not-a-sal") is None
